name: Arrows4Players 
version: 1.0
description: Arrows from any source can be picked up to be reused now. Oh yeah..
author: Sycholic
website: http://not.com
main: com.sycholic.arrows4players.PoachArrows
database: false

